version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_NAME
      - APP_VERSION
      - DB_URL
      - JWT_SECRET_KEY
      - JWT_ALGORITHM
      - USER_ACCESS_TOKEN_EXPIRE_MINUTES
      - REDIS_URL
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - ENABLE_USING_CACHE
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=$$POSTGRES_PASSWORD pg_isready -h 127.0.0.1 -U docker -d gis"

  redis:
    image: redis
    expose:
      - 6379
    ports: 
      - 6379:6379
    environment:
      - TZ=Asia/Tehran
    
  
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    depends_on:
      - redis


volumes:
  postgres_data: