version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: on-failure

  redis:
    image: redis
    expose:
      - 6379
    ports: 
      - 6379:6379
    environment:
      - TZ=Asia/Tehran
    
  
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    depends_on:
      - redis


volumes:
  postgres_data: